import 'package:mobx/mobx.dart';

part 'home_store.g.dart';

class HomeStore = HomeStoreBase with _$HomeStore;

abstract class HomeStoreBase with Store {
  @observable
  int counter = 0;

  String readme =
      "# Sql Analyzer Project                                                                                        "
      "Welcome to the Sql Analyzer documentation!                                                                    "
      "This documentation covers the configuration and use of this project.                                          "
      "                                                                                                              "
      "## Running on Windows                                                                                         "
      "The sql_analyzer required two arguments.<br>                                                                  "
      "  -i or --input: the name of the file to analyze.<br>                                                         "
      "  -t or --type: type of input file, query or sequence.<br>                                                    "
      "                                                                                                              "
      "Examples:                                                                                                     "
      "```shell                                                                                                      "
      "sql_analyzer.exe -i "
      'query.json'
      " -t "
      'query'
      "                                                                   "
      "```                                                                                                           "
      "```shell                                                                                                      "
      "sql_analyzer.exe -i "
      'sequence.json'
      " -t "
      'sequence'
      "                                                             "
      "```                                                                                                           "
      "                                                                                                              "
      "## Structure of the Project                                                                                   "
      "The Sql Analyzer Project is organized following the structure:                                                "
      "                                                                                                              "
      "```shell                                                                                                      "
      "-sql_analyzer                                                                                                 "
      "  |_configurations                                                                                            "
      "  |_data_access                                                                                               "
      "  |_domain                                                                                                    "
      "  |_file_manager                                                                                              "
      "  |_parser                                                                                                    "
      "  |_ldx_analyzer                                                                                              "
      "```                                                                                                           "
      "## Configurations                                                                                             "
      " The Configuration manage the application settings, the application arguments and the database configuration. "
      "                                                                                                              "
      " ### appSettings.Json                                                                                         "
      " ```shell                                                                                                     "
      "{                                                                                                             "
      "  "
      "QuestionDirectory"
      ": "
      "Questions"
      ",                                                                           "
      "  "
      "UserQuestionDirectory"
      ": "
      "UserQuestions"
      ",                                                                   "
      "  "
      "SequenceDirectory"
      ": "
      "Sequences"
      ",                                                                           "
      "  "
      "ReportDirectory"
      ": "
      "Reports"
      ",                                                                               "
      "  "
      "LogDirectory"
      ": "
      "Logs"
      ",                                                                                     "
      "  "
      "LogFileName"
      ": "
      "sql_analyzer.log"
      ",                                                                          "
      "  "
      "LogDetailLevel"
      ": "
      "high"
      ",                                                                                   "
      "  "
      "UserProfile"
      ": "
      "admin"
      ",                                                                                     "
      "  "
      "FirebirdPrefix"
      ": "
      "@"
      ",                                                                                      "
      "  "
      "SqlServerPrefix"
      ": "
      "@"
      ",                                                                                     "
      "  "
      "OraclePrefix"
      ": "
      ":"
      ",                                                                                        "
      "  "
      "SqLitePrefix"
      ": "
      ":"
      "                                                                                         "
      "}                                                                                                             "
      "```                                                                                                           "
      "**QuestionDirectory:** Name of the Question folder.<br>                                                       "
      "**UserQuestionDirectory:** Name of the UserQuestion folder.<br>                                               "
      "**SequenceDirectory:** Name of the Sequence flder.<br>                                                        "
      "**ReportDirectory:** Name of the Report folder.<br>                                                           "
      "**LogDirectory:** Name of the Log folder.<br>                                                                 "
      "**LogFileName:** Name of the log file.<br>                                                                    "
      "**LogDetailLevel:** Level of the log. [low|medium|high]<br>                                                   "
      "**UserProfile:** The User profile. [user|admin].<br>                                                          "
      "**FirebirdPrefix:** The Firebird prefix for the parameterized queries.<br>                                    "
      "**SqlServerPrefix:** The SqlServer prefix for the parameterized queries.<br>                                  "
      "**OraclePrefix:** The Oracle prefix for the parameterized queries.<br>                                        "
      "**SqLitePrefix:** The SqLite prefix for the parameterized queries.<br>                                        "
      "                                                                                                              "
      "### databaseConfig.json                                                                                       "
      "The database configuration file contains two fields, <br>                                                     "
      "- ConnectionString: String containing the host, database, user, password etc.<br>                             "
      "- DataBaseType: The type of database, can be "
      "oracle"
      ", "
      "firebird"
      " or "
      "sqlserver"
      ".<br>                         "
      "```shell                                                                                                      "
      "{                                                                                                             "
      "  "
      "ConnectionString"
      ": "
      ",                                                                                     "
      "  "
      "DataBaseType"
      ": "
      "                                                                                          "
      "}                                                                                                             "
      "```                                                                                                           "
      "## Questions                                                                                                  "
      "The Questions folder contains the questions used to extract the requested informations.<br>                   "
      "The Question file have the following structure:                                                               ";
}
